### ISSUE TITLE
Error when starting pycardsyncer

### ISSUE THREAD

**Issue by mrjovanovic** [geier/pycarddav#108]
I get the following error when starting pycardsyncer. I installed by cloning the git repo and then running ./setup.py install

    Traceback (most recent call last):
      File "/usr/local/bin/pycardsyncer", line 4, in <module>
        __import__('pkg_resources').run_script('pyCardDAV==0.7.0.dev-15-ge124b51-dirty', 'pycardsyncer')
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445, in run_script
        exec(script_code, namespace, namespace)
      File "/usr/local/lib/python2.7/dist-packages/pyCardDAV-0.7.0.dev_15_ge124b51_dirty-py2.7.egg/EGG-INFO/scripts/pycardsyncer", line 59, in <module>
    
    TypeError: __str__ returned non-string (type Error)

I am really a beginner, but would like some help in getting this to work. Thanks!

**Comment by geier** [comment]
Interesting, I've never seen an error like this before and honestly have no clue what error you have found here. If you have `pip` installed, can you try installing pycarddav with `pip install .` (from within the pycarddavd directory)?

**Comment by geier** [comment]
closed because lack of activity, please reopen if needed
