### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by abrumloop** [geier/pycarddav#111]
Hi,

i just installed pycarddav via pip and run into following error:

DEBUG:root:Using configuration from .config/pycard/pycard.conf
DEBUG:root:Ignoring query:where in configuration file
DEBUG:root:Ignoring default:debug in configuration file
DEBUG:root:Using configuration:
DEBUG:root:	accounts:
DEBUG:root:		auth: basic
DEBUG:root:		name: OwnCloud Kontakte
DEBUG:root:		resource: https://<url>/owncloud/remote.php/carddav/addressbooks/<uname>/kontakte/
DEBUG:root:		user: <uname>
DEBUG:root:		verify: True
DEBUG:root:		write_support: False
DEBUG:root:	debug: True
DEBUG:root:	filename: .config/pycard/pycard.conf
DEBUG:root:	sqlite:
DEBUG:root:		path: /home/<uname>/.local/share/pycard/abook.db
DEBUG:root:	sync:
DEBUG:root:		accounts: set(['OwnCloud Kontakte'])
DEBUG:root:start syncing account OwnCloud Kontakte
Traceback (most recent call last):
  File "/usr/bin/pycardsyncer", line 55, in <module>
    sync(conf)
  File "/usr/lib/python2.7/site-packages/pycarddav/controllers/sync.py", line 44, in sync
    auth=conf.account.auth)
  File "/usr/lib/python2.7/site-packages/pycarddav/carddav.py", line 101, in __init__
    **self._settings)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077458:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 unrecognized name

is there any solution for this error? 

greet abrumloop

**Comment by geier** [comment]
Sadly, this is not under our control. It probably is an [requests](https://github.com/kennethreitz/requests) issue, but I'm not sure it's under their control either.

A quick search for `tlsv1 unrecognized name` lets me suspect this is an [SNI issue again](https://github.com/geier/pycarddav/issues/58).

**Comment by abrumloop** [comment]
Thank you for your quick response.
