### ISSUE TITLE
Can't sync

### ISSUE THREAD

**Issue by nielsk** [geier/pycarddav#115]
Hi,

I am trying to sync my account from mailbox.org and it works with Evolution but not with pycarddav.
When I do a pycardsyncer --debug I get the following output:

DEBUG:root:Using configuration from /home/user/.config/pycard/pycard.conf
DEBUG:root:Ignoring default:debug in configuration file
DEBUG:root:Using configuration:
DEBUG:root:	accounts:
DEBUG:root:		auth: basic
DEBUG:root:		name: Contacts
DEBUG:root:		passwd_cmd: 
DEBUG:root:		resource: https://dav.mailbox.org/carddav/27/
DEBUG:root:		user: myuser@mailbox.org
DEBUG:root:		verify: True
DEBUG:root:		write_support: False
DEBUG:root:	debug: True
DEBUG:root:	filename: /home/nik/.config/pycard/pycard.conf
DEBUG:root:	sqlite:
DEBUG:root:		path: /home/nik/.config/pycard/abook.db
DEBUG:root:	sync:
DEBUG:root:		accounts: set(['Contacts'])
DEBUG:root:start syncing account Contacts
DEBUG:root:made sure version table exists
DEBUG:root:made sure accounts table exists 
Traceback (most recent call last):
  File "/usr/bin/pycardsyncer", line 55, in <module>
    sync(conf)
  File "build/bdist.linux-x86_64/egg/pycarddav/controllers/sync.py", line 50, in sync
  File "build/bdist.linux-x86_64/egg/pycarddav/carddav.py", line 140, in get_abook
  File "build/bdist.linux-x86_64/egg/pycarddav/carddav.py", line 253, in _process_xml_props
  File "lxml.etree.pyx", line 3083, in lxml.etree.XML (src/lxml/lxml.etree.c:70338)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106403)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105194)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99876)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94350)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95786)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:95065)
lxml.etree.XMLSyntaxError: None

An abook.db will be created but it is only 3KByte in size. In the past I synced with owncloud and the file should be more like 13MB…

**Comment by geier** [comment]
I won't fix this (see #92), but I'm happy to accept pull requests on this.

As an interim solution use I suggest to give [khard](https://github.com/scheibler/khard/) a try, which should most features of pycarddav and than some.

 The only feature missing from khard is probably something like *pycard_import*, I'll try to send a pull request for that ASAP.

**Comment by nielsk** [comment]
Thanks. vcardsyncer/khard seems to work. I am still trying to figure out how to show a whole card and not only a tiny bit of it but at least for mutt-completion it works.

**Comment by geier** [comment]
I think you can type `khard details -s SEARCHTERM`

**Comment by nielsk** [comment]
Thanks, that works
